version: '3.7'

services:
  mongo:
    container_name: mongo
    restart: unless-stopped
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=test
    ports:
      - '27888:27017'
    volumes:
      - ./data/mongo:/data/db
